# Generated by Django 3.0.7 on 2020-07-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='name',
            field=models.TextField(default='_'),
        ),
        migrations.AlterField(
            model_name='main',
            name='email',
            field=models.TextField(default='_'),
        ),
        migrations.AlterField(
            model_name='main',
            name='f_name',
            field=models.TextField(default='_'),
        ),
        migrations.AlterField(
            model_name='main',
            name='l_name',
            field=models.TextField(default='_'),
        ),
    ]
