# Generated by Django 3.0.7 on 2020-08-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20200728_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='age',
            field=models.IntegerField(default='_'),
        ),
    ]
