# Generated by Django 3.0.7 on 2020-08-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_auto_20200802_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
