# Generated by Django 3.0.7 on 2020-08-04 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_auto_20200804_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='age',
        ),
    ]
