# Generated by Django 3.0.7 on 2020-08-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_main_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
