# Generated by Django 3.0.7 on 2020-08-04 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_auto_20200804_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='YOB',
        ),
    ]
